### ISSUE TITLE
Issues with getting a base64

### ISSUE THREAD

**Issue by KenwoodFox** [team-tumbleweed/gdrive-upload-action#11]
With any combination of base64 encoding i run into issues. this may be due to linux having slightly different encoding tools than mac? Once i figure this out. Ill make a PR to include a note in the docs
![image](https://user-images.githubusercontent.com/31870999/154319666-02912d82-ba29-4a32-8660-a47a92417cec.png)

The last character here always looks odd when using the included command on linux, witch produces a encoding sveral thousand letters long 
![image](https://user-images.githubusercontent.com/31870999/154319768-66adf926-1e8c-416d-bed0-16745fc9a391.png)

Alternativly, this syntax 
```
echo <file.json>| base64 -w 0
```
produces a much shorter encoding still with the strange character 
![image](https://user-images.githubusercontent.com/31870999/154319952-d17f8bab-cfa0-47a7-a46b-7ef1c30a25f1.png)

hexdump says last two chars are this 
![image](https://user-images.githubusercontent.com/31870999/154320191-820749c2-eaf4-4549-b2a2-3d29605cbb7a.png)

not sure whats helpful here and whats not, thanks for reading, will update you

**Comment by mathisve** [comment]
Hi,

We've been having a lot of issues with base64 encoding the credentials.
Maybe it's not a bad idea to add an option to add credentials in plaintext.

I'm pretty swamped with other stuff, but if I have time this weekend I might attempt to make that a reality.

**Comment by KenwoodFox** [comment]
Sorry to add more to your plate, i may not be able to help with that but i suspect that the linux base64 encoding is just maybe a tad different than the BSD one/mac? What would an appropriate encoding look like i can spend some time testing to see if i can get it working. Id be more than happy to add some different command strings to the readme

**Comment by KenwoodFox** [comment]
Ran a diff after piping back and forth through base64 with the same string in readme, looks like its not capturing the newline 
![image](https://user-images.githubusercontent.com/31870999/154322691-46220e10-8961-42b1-bd43-2f9f208a85aa.png)

**Comment by KenwoodFox** [comment]
![image](https://user-images.githubusercontent.com/31870999/154327840-6f2cf3c3-be27-42f9-9272-fba61828fbea.png)

bleh

**Comment by Wazbat** [comment]
Also having this issue with linux. I just had to use an online converter to test and that worked

I think supporting raw keys directly would be a good idea. I've seen other actions do this. I'd try to change that myself but I've never touched go

**Comment by mathisve** [comment]
Yeah I think adding an option for a 'non-encoded' secret might be the only fix.
Working on it.

**Comment by mathisve** [comment]
Fixed with c6928de!
