### ISSUE TITLE
add overwrite option

### ISSUE THREAD

**Issue by mathisve** [team-tumbleweed/gdrive-upload-action#17]
When uploading a file with a filename that already exists, it will create another file with the same name in the same directory (folder). 

This could be undesired behavior and there should be an option to overwrite a file.
<img width="711" alt="image" src="https://user-images.githubusercontent.com/11077185/197376401-5974e7e2-4c90-44f3-8e17-fbae2a0a54ef.png">

**Comment by shmpwk** [comment]
@mathisve 
I found this action allows you to overwrite the file.
https://github.com/adityak74/google-drive-upload-git-action#overwrite

**Comment by mathisve** [comment]
Hi, that repository is a fork of this one. They originally made a PR (#9) but due to some comments that were never addressed, this repository was never merged. I still intend to implement this feature, but due to a lack of time and motivation that hasn't happened yet.
