### ISSUE TITLE
Download from drive

### ISSUE THREAD

**Issue by aghand0ur** [team-tumbleweed/gdrive-upload-action#23]
Hi @mathisve,

Would it be possible to use your repo to download files from drive inside github actions?

Ali

**Comment by mathisve** [comment]
Unfortunately not. This Github Action only allows you to upload artifacts to Google drive

**Comment by aghand0ur** [comment]
If the file is publicly shared, then this can be done the following way:

```
      - name: Download sql dump from gdrive
        run: |
          pip install gdown
          gdown --id [fild id]
```
