### ISSUE TITLE
error on fetching jwt

### ISSUE THREAD

**Issue by frank-w** [team-tumbleweed/gdrive-upload-action#28]
Hi,

i get this error:

Error: fetching JWT credentials failed with error: invalid character 'e' looking for beginning of value

how can i trace the issue?

i created a new project with service account, added a new json-key, encoded base64, enabled api and share the gdrive-folder with the service-account email

regards Frank

**Comment by mathisve** [comment]
Hi Frank,

Unfortunately there is little I can do to help you with this problem as I don't want to ask you to share your Service Account credentials file with me (I'm sure you know why).

But it seems the error is related to the unmarshalling of the JSON. Are you sure you are downloading the correct file in the correct format?

**Comment by frank-w** [comment]
I switched to adityak74/google-drive-upload-git-action and there my token works

Thx for answering
