### ISSUE TITLE
Base64 Error Always

### ISSUE THREAD

**Issue by adityak74** [team-tumbleweed/gdrive-upload-action#3]
I keep getting the base64 error always. I did check with Go Repl as well to confirm if my string is decoding correctly and it is. 

<img width="1295" alt="Screen Shot 2021-04-16 at 4 57 06 PM" src="https://user-images.githubusercontent.com/5231288/115087919-c75dca00-9ed4-11eb-901f-00beb7a510ff.png">

<img width="1680" alt="Screen Shot 2021-04-16 at 4 58 52 PM" src="https://user-images.githubusercontent.com/5231288/115088077-068c1b00-9ed5-11eb-9dec-58c78e9e0a4b.png">

**Comment by KenwoodFox** [comment]
Did you ever fix this?

**Comment by wdcs-harshitpadalia** [comment]
I am facing same issue as well

**Comment by mathisve** [comment]
We addressed this (mostly through documentation) in 320a21dc0c0ae85d883ada3f0ccf91f0e099f122.
@wdcs-harshitpadalia what command are you using to generate the base64 encoded string, and are you using the correct Github actions inputs?
